from evennia import DefaultRoom

from services.room_presentation_engine import render_room_state_text


class Room(DefaultRoom):
    """Atomic persistent location for Siza."""

    def at_object_creation(self):
        super().at_object_creation()
        self.db.room_id = None
        self.db.zone_id = None
        self.db.region_id = None
        self.db.settlement_id = None
        self.db.district_id = None
        self.db.canon_status = "prototype"

        # Obvious authored sensory facts. Entering/looking does not roll for these.
        self.db.sensory_facts = {
            "sight": [],
            "hearing": [],
            "smell": [],
            "touch": [],
            "taste": [],
        }

        # Physical orientation data for prose. Missing fields mean unknown, not absent.
        self.db.space_profile = {
            "room_type": None,
            "scale": None,
            "geometry": None,
            "orientation": None,
            "focal_points": [],
            "status": "prototype",
        }

        # Authored uncertain facts. PER may reveal these, but can never create new ones.
        # Each entry can contain: id, sense, difficulty, target, keywords, fact.
        self.db.perception_facts = []

        # Persistent work requests generated by structures/locations. The Decision Layer
        # may derive JOB goals from these when an NPC's job_id matches the task.
        self.db.job_tasks = []

        self.db.conditions = {}
        self.db.world_state = {}

        # Optional authored text fragments whose visibility depends only on persistent
        # room world_state. They augment, never replace, the room's normal description.
        self.db.state_presentations = []

    def return_appearance(self, looker, **kwargs):
        """Preserve Evennia's normal room appearance and append active state-authored text."""
        base = super().return_appearance(looker, **kwargs)
        state_text = render_room_state_text(self)
        if not state_text:
            return base
        if not base:
            return state_text
        return f"{base}\n{state_text}"
