(function(global){
'use strict';

const VERSION='1.5.0';
const legacyFullCardImages=Object.freeze({
 mist:'cards-v0514/niebla_de_sal.webp?v=0514',spark:'cards-v0514/chispa_del_estuario.webp?v=0612',servitor:'cards-v0514/servidor_ahogado.webp?v=0514',ignimite:'cards-v0514/ignimite.webp?v=0612',counter:'cards-v0514/negacion_pictomantica.webp?v=0514',prism:'cards-v0514/prisma_de_enfoque.webp?v=0514',watcher:'cards-v0514/vigia_de_la_marea.webp?v=0514',smuggler:'cards-v0514/contrabandista_carmesi.webp?v=0612',tideblade:'cards-v0514/espada_de_bajamar.webp?v=0612',leviathan:'cards-v0514/leviatan_de_la_campana.webp?v=0514',dock:'cards-v0514/muelle_sumergido.webp?v=0514',cinder:'cards-v0514/erial_de_ceniza.webp?v=0514',queen:'cards-v0514/memoria_de_la_reina_ahogada.webp?v=0515'
});
function equipmentTokenImage(glyph,label,accent){const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 140 196"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#102b3e"/><stop offset="1" stop-color="#06131d"/></linearGradient></defs><rect width="140" height="196" rx="12" fill="url(#g)"/><rect x="5" y="5" width="130" height="186" rx="10" fill="none" stroke="#b88a42" stroke-width="4"/><rect x="12" y="12" width="116" height="172" rx="8" fill="none" stroke="${accent}" stroke-width="2" opacity=".85"/><text x="70" y="105" text-anchor="middle" font-size="62" fill="#f3e5be" font-family="Georgia,serif">${glyph}</text><text x="70" y="160" text-anchor="middle" font-size="14" fill="#d5c28f" font-family="Georgia,serif">${label}</text></svg>`;return'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function card(data){const pips=Object.freeze({...data.pips}),effects=data.effects?Object.freeze(data.effects.map(effect=>Object.freeze({...effect}))):undefined;return Object.freeze({...data,pips,...(effects?{effects}:{})})}
const RESERVE_TEXT='Las Lands no se juegan al Battlefield. Permanecen en la mano y sólo se consumen como Mana Burn para aumentar una tirada de Manafestation fallida.';
const cards=Object.freeze([
 card({id:'mist',legacyFullCardImage:legacyFullCardImages.mist,name:'Niebla de Sal',type:'Instant',difficulty:5,pips:{U:1},text:'Roba una carta.',flavor:'La marea guarda secretos incluso de quienes viven de ella.',role:'draw',art:'blue',glyph:'≈',effects:[{event:'resolve',type:'draw',target:'self',amount:1}]}),
 card({id:'spark',legacyFullCardImage:legacyFullCardImages.spark,name:'Chispa del Estuario',type:'Instant',difficulty:5,pips:{R:1},text:'Inflige 2 de daño al Personaje rival.',flavor:'Una chispa basta cuando el aire sabe a sal.',role:'removal',art:'red',glyph:'✦',effects:[{event:'resolve',type:'damage-character',target:'opponent',amount:2}]}),
 card({id:'servitor',legacyFullCardImage:legacyFullCardImages.servitor,name:'Servidor Ahogado',type:'Creature',subtype:'Ahogado',difficulty:6,pips:{U:1},power:2,toughness:2,text:'Cuando entra, observa la carta superior de tu Library.',flavor:'No respira. Recuerda.',role:'threat',art:'blue',glyph:'☠',effects:[{event:'enter',type:'observe-top',target:'self'}]}),
 card({id:'ignimite',legacyFullCardImage:legacyFullCardImages.ignimite,name:'Ignimite',type:'Creature',subtype:'Elemental',difficulty:6,pips:{R:1},power:1,toughness:1,text:'Cuando hace daño de combate, obtiene +1/+1.',flavor:'Toda llama aprende de aquello que consume.',role:'threat',art:'red',glyph:'♨',effects:[{event:'combat-damage',type:'add-power-counter',amount:1}]}),
 card({id:'counter',legacyFullCardImage:legacyFullCardImages.counter,name:'Negación Pictomántica',type:'Instant',difficulty:6,pips:{U:2},text:'Contrarresta el spell objetivo.',flavor:'No toda memoria merece cruzar.',role:'counter',art:'blue',glyph:'⊘',effects:[{event:'resolve',type:'counter-stack-target'}]}),
 card({id:'prism',legacyFullCardImage:legacyFullCardImages.prism,finalCardImage:equipmentTokenImage('◇','PRISMA','#5aa8cf'),name:'Prisma de Enfoque',type:'Artifact',difficulty:6,pips:{},text:'Agota: +1 a una Manafestation Azul.',flavor:'El cristal no crea poder. Lo convence de tomar forma.',role:'ramp',art:'multi',glyph:'◇',effects:[{event:'manifest-roll',type:'manifest-bonus',amount:1,requiresPip:'U',exhaustSource:true}]}),
 card({id:'watcher',legacyFullCardImage:legacyFullCardImages.watcher,name:'Vigía de la Marea',type:'Creature',subtype:'Soldado',difficulty:7,pips:{U:2},power:2,toughness:4,text:'Defensor de las rutas sumergidas.',flavor:'La costa nunca duerme; sólo cambia de guardia.',role:'threat',art:'blue',glyph:'♜'}),
 card({id:'smuggler',legacyFullCardImage:legacyFullCardImages.smuggler,name:'Contrabandista Carmesí',type:'Creature',subtype:'Humano',difficulty:7,pips:{R:2},power:3,toughness:2,text:'Siempre que ataque, inflige 1 de daño adicional al Personaje defensor.',flavor:'No existe puerto sin una segunda aduana.',role:'threat',art:'red',glyph:'⚔',effects:[{event:'attack-declared',type:'damage-character',target:'opponent',amount:1}]}),
 card({id:'tideblade',legacyFullCardImage:legacyFullCardImages.tideblade,finalCardImage:equipmentTokenImage('†','ESPADA','#6f9bb7'),name:'Espada de Bajamar',type:'Artifact',difficulty:6,pips:{U:1},equipCost:1,text:'La criatura equipada obtiene +2/+0. Equipar {1}.',flavor:'Forjada donde el agua revela lo que la marea quiso ocultar.',role:'utility',art:'blue',glyph:'†',effects:[{event:'equipped',type:'modify-power',amount:2}]}),
 card({id:'leviathan',legacyFullCardImage:legacyFullCardImages.leviathan,name:'Leviatán de la Campana',type:'Creature',subtype:'Leviatán',difficulty:8,pips:{U:3},power:7,toughness:7,text:'Al entrar, devuelve otro permanente a la mano de su dueño.',flavor:'La campana no lo llama. Le recuerda que alguna vez estuvo despierto.',role:'finisher',art:'blue',glyph:'Ω',effects:[{event:'enter',type:'bounce-other-permanent'}]}),
 card({id:'dock',legacyFullCardImage:legacyFullCardImages.dock,name:'Muelle Sumergido',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'Cada tabla guarda el peso de quienes nunca regresaron.',role:'land',art:'land',glyph:'⌁'}),
 card({id:'cinder',legacyFullCardImage:legacyFullCardImages.cinder,name:'Erial de Ceniza',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'El fuego también deja territorio.',role:'land',art:'land',glyph:'△'}),
 card({id:'queen',legacyFullCardImage:legacyFullCardImages.queen,name:'Memoria de la Reina Ahogada',type:'Creature',subtype:'Avatar',difficulty:8,pips:{U:3},power:5,toughness:5,text:'Al entrar, roba dos cartas y luego descarta una.',flavor:'La corona sobrevivió porque nadie recordó enterrarla.',role:'finisher',art:'multi',glyph:'♛',adventureUnlock:true,effects:[{event:'enter',type:'draw',target:'self',amount:2},{event:'enter',type:'discard',target:'self',amount:1,choice:'owner'}]}),
 card({id:'dhk_familiar_de_practica',name:'Familiar de Práctica',type:'Creature',subtype:'Familiar',difficulty:4,pips:{},power:1,toughness:1,text:'Invocación básica de entrenamiento.',flavor:'Primero se aprende a sostener la forma.',role:'starter',art:'multi',glyph:'◈'}),
 card({id:'dhk_lectura_de_campo',name:'Lectura de Campo',type:'Instant',difficulty:5,pips:{U:1},text:'Roba una carta.',flavor:'La observación correcta ahorra una batalla.',role:'starter',art:'blue',glyph:'⌕',effects:[{event:'resolve',type:'draw',target:'self',amount:1}]}),
 card({id:'dhk_interrupcion_de_protocolo',name:'Interrupción de Protocolo',type:'Instant',difficulty:6,pips:{U:2},text:'Contrarresta el spell objetivo.',flavor:'Darkhaven enseña primero cuándo decir no.',role:'starter',art:'blue',glyph:'⊘',effects:[{event:'resolve',type:'counter-stack-target'}]}),
 card({id:'dhk_prisma_de_servicio',finalCardImage:equipmentTokenImage('◇','SERVICIO','#89a7ba'),name:'Prisma de Servicio',type:'Artifact',difficulty:5,pips:{},text:'Agota: obtén +1 a una tirada de Manafestación.',flavor:'Equipo estándar, resultado verificable.',role:'starter',art:'multi',glyph:'◇',effects:[{event:'manifest-roll',type:'manifest-bonus',amount:1,exhaustSource:true}]}),
 card({id:'dhk_spellweapon_de_servicio',finalCardImage:equipmentTokenImage('†','SERVICIO','#b9a16d'),name:'Spellweapon de Servicio',type:'Artifact',subtype:'Equipment',difficulty:5,pips:{},equipCost:1,text:'La Invocación equipada obtiene +1/+0. Equipar {1}.',flavor:'Una herramienta antes que un trofeo.',role:'starter',art:'multi',glyph:'†',effects:[{event:'equipped',type:'modify-power',amount:1}]}),
 card({id:'dhk_ojo_de_baliza',name:'Ojo de Baliza',type:'Creature',subtype:'Familiar',difficulty:5,pips:{U:1},power:1,toughness:2,text:'Al entrar, observa la carta superior de tu Library.',flavor:'Ve primero. Decide después.',role:'starter',art:'blue',glyph:'◉',effects:[{event:'enter',type:'observe-top',target:'self'}]}),
 card({id:'dhk_eco_de_rastreo',name:'Eco de Rastreo',type:'Creature',subtype:'Echo',difficulty:6,pips:{U:1},power:2,toughness:2,text:'Al entrar, roba una carta.',flavor:'Cada huella conserva una pregunta.',role:'starter',art:'blue',glyph:'⌁',effects:[{event:'enter',type:'draw',target:'self',amount:1}]}),
 card({id:'dhk_ancla_de_retorno',finalCardImage:equipmentTokenImage('⌁','ANCLA','#5aa8cf'),name:'Ancla de Retorno',type:'Artifact',difficulty:7,pips:{U:2},text:'Al entrar, devuelve otro permanente a la mano de su dueño.',flavor:'Fija el lugar al que debe volver una forma.',role:'starter',art:'blue',glyph:'⌁',effects:[{event:'enter',type:'bounce-other-permanent'}]}),
 card({id:'dhk_corte_de_senal',name:'Corte de Señal',type:'Instant',difficulty:6,pips:{U:1},text:'El rival descarta una carta.',flavor:'Una orden incompleta también puede ser una defensa.',role:'starter',art:'blue',glyph:'╱',effects:[{event:'resolve',type:'discard',target:'opponent',amount:1,choice:'owner'}]}),
 card({id:'dhk_archivo_de_guardia',name:'Archivo de Guardia',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'Cada turno deja constancia.',role:'land',art:'land',glyph:'▤'}),
 card({id:'dhk_plataforma_de_relevo',name:'Plataforma de Relevo',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'Nadie vigila solo.',role:'land',art:'land',glyph:'⌂'}),
 card({id:'dhk_ignimite_de_ejercicio',name:'Ignimite de Ejercicio',type:'Creature',subtype:'Elemental',difficulty:5,pips:{R:1},power:1,toughness:1,text:'Cuando hace daño de combate, obtiene +1/+1.',flavor:'El blanco de práctica también aprende.',role:'starter',art:'red',glyph:'♨',effects:[{event:'combat-damage',type:'add-power-counter',amount:1}]}),
 card({id:'dhk_mastin_de_impacto',name:'Mastín de Impacto',type:'Creature',subtype:'Beast',difficulty:6,pips:{R:1},power:3,toughness:2,text:'Criatura de entrenamiento orientada a presión y combate limpio.',flavor:'Corre hacia el hueco antes de que exista.',role:'starter',art:'red',glyph:'◆'}),
 card({id:'dhk_eco_de_asalto',name:'Eco de Asalto',type:'Creature',subtype:'Echo',difficulty:6,pips:{R:1},power:2,toughness:2,text:'Cuando ataque, inflige 1 de daño al Personaje defensor.',flavor:'El primer golpe sigue resonando.',role:'starter',art:'red',glyph:'»',effects:[{event:'attack-declared',type:'damage-character',target:'opponent',amount:1}]}),
 card({id:'dhk_descarga_de_ruptura',name:'Descarga de Ruptura',type:'Instant',difficulty:5,pips:{R:1},text:'Inflige 2 de daño al Personaje rival.',flavor:'La doctrina pide una salida, no elegancia.',role:'starter',art:'red',glyph:'ϟ',effects:[{event:'resolve',type:'damage-character',target:'opponent',amount:2}]}),
 card({id:'dhk_galeria_de_entrenamiento',name:'Galería de Entrenamiento',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'El muro recuerda cada impacto.',role:'land',art:'land',glyph:'▱'}),
 card({id:'dhk_hangar_de_salida',name:'Hangar de Salida',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'La puerta ya estaba abierta.',role:'land',art:'land',glyph:'△'}),
 card({id:'dhk_sabueso_de_umbral',name:'Sabueso de Umbral',type:'Creature',subtype:'Familiar',difficulty:5,pips:{U:1},power:1,toughness:3,text:'Invocación defensiva de entrenamiento.',flavor:'No necesita perseguir lo que debe detener.',role:'starter',art:'blue',glyph:'◊'}),
 card({id:'dhk_custodio_lumex',name:'Custodio Lumex',type:'Creature',subtype:'Construct',difficulty:7,pips:{U:1},power:2,toughness:4,text:'Constructo de alta resistencia.',flavor:'La luz se mantiene porque algo sostiene el marco.',role:'starter',art:'blue',glyph:'▣'}),
 card({id:'dhk_bastion_pictomantico',name:'Bastión Pictomántico',type:'Creature',subtype:'Construct',difficulty:8,pips:{U:2,R:1},power:3,toughness:6,text:'Invocación de desarrollo tardío, difícil de retirar.',flavor:'Tres cristales fijan una sola negativa.',role:'starter',art:'multi',glyph:'♜'}),
 card({id:'dhk_contraimpulso',name:'Contraimpulso',type:'Instant',difficulty:5,pips:{U:2},text:'Contrarresta el spell objetivo.',flavor:'La fuerza se pierde cuando no encuentra resolución.',role:'starter',art:'blue',glyph:'⊘',effects:[{event:'resolve',type:'counter-stack-target'}]}),
 card({id:'dhk_patio_de_contencion',name:'Patio de Contención',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'Cada salida está medida.',role:'land',art:'land',glyph:'□'}),
 card({id:'dhk_camara_de_frames',name:'Cámara de Frames',type:'Land',pips:{},text:RESERVE_TEXT,flavor:'Las formas esperan detrás del vidrio.',role:'land',art:'land',glyph:'▦'})
]);
function get(id){return cards.find(entry=>entry.id===id)||null}function all(){return cards.slice()}
global.SizaCardCatalog=Object.freeze({VERSION,cards,legacyFullCardImages,get,all});
})(window);
