(function(){
"use strict";
var STORE="pokerol_pokemon_creator_v1";
function read(){try{return JSON.parse(localStorage.getItem(STORE)||"null")}catch(e){return null}}
function save(s){localStorage.setItem(STORE,JSON.stringify(s))}
function selectedId(){var node=document.querySelector("#itemList .item.sel[data-id]");return node&&node.getAttribute("data-id")}
function spriteDefaults(p){var dex=Number(p.dex_number)||0;if(!dex)return{front:"",back:"",icon:"",scale:1};return{front:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"+dex+".png",back:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/"+dex+".png",icon:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"+dex+".png",scale:1.25}}
function ensureSprites(){var s=read();if(!s||!Array.isArray(s.pokemon))return false;var changed=false;s.pokemon.forEach(function(p){if(!p.sprite||typeof p.sprite!=="object"){p.sprite=spriteDefaults(p);changed=true}else{var d=spriteDefaults(p);["front","back","icon"].forEach(function(k){if(p.sprite[k]===undefined){p.sprite[k]=d[k];changed=true}});if(p.sprite.scale===undefined){p.sprite.scale=d.scale;changed=true}}});if(changed)save(s);return changed}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]})}
function mount(){ensureSprites();var id=selectedId(),state=read();if(!id||!state||!Array.isArray(state.pokemon))return;var p=state.pokemon.find(function(x){return x.editor_id===id});if(!p)return;var editor=document.getElementById("editor");if(!editor)return;var old=document.getElementById("pokerol-sprite-card");if(old)old.remove();var sp=p.sprite||spriteDefaults(p);var card=document.createElement("div");card.id="pokerol-sprite-card";card.className="card";card.innerHTML='<h3>Battle Sprite</h3><div class="grid2"><div><div class="field"><label>Sprite frente</label><input id="pkSpriteFront" value="'+esc(sp.front||"")+'"></div><div class="field"><label>Sprite espalda</label><input id="pkSpriteBack" value="'+esc(sp.back||"")+'"></div><div class="field"><label>Icono</label><input id="pkSpriteIcon" value="'+esc(sp.icon||"")+'"></div><div class="field"><label>Escala de batalla</label><input id="pkSpriteScale" type="number" step="0.05" min="0.25" max="4" value="'+esc(sp.scale||1)+'"></div><button id="pkSpriteAuto" class="btn">Auto por Pokédex</button></div><div><div class="note">El sprite de frente se usa para rivales/salvajes; el de espalda para tu Pokémon.</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px"><div style="min-height:150px;display:grid;place-items:center;background:#091018;border:1px solid #2d3a4e;border-radius:8px"><img id="pkSpritePreviewFront" src="'+esc(sp.front||"")+'" style="max-width:140px;max-height:140px;image-rendering:pixelated"></div><div style="min-height:150px;display:grid;place-items:center;background:#091018;border:1px solid #2d3a4e;border-radius:8px"><img id="pkSpritePreviewBack" src="'+esc(sp.back||sp.front||"")+'" style="max-width:140px;max-height:140px;image-rendering:pixelated"></div></div></div></div>';
editor.insertBefore(card,editor.firstChild);
function write(){var s=read();if(!s)return;var q=s.pokemon.find(function(x){return x.editor_id===id});if(!q)return;q.sprite={front:document.getElementById("pkSpriteFront").value.trim(),back:document.getElementById("pkSpriteBack").value.trim(),icon:document.getElementById("pkSpriteIcon").value.trim(),scale:Math.max(.25,Math.min(4,Number(document.getElementById("pkSpriteScale").value)||1))};save(s);document.getElementById("pkSpritePreviewFront").src=q.sprite.front;document.getElementById("pkSpritePreviewBack").src=q.sprite.back||q.sprite.front}
["pkSpriteFront","pkSpriteBack","pkSpriteIcon","pkSpriteScale"].forEach(function(k){var e=document.getElementById(k);if(e)e.addEventListener("input",write)});document.getElementById("pkSpriteAuto").onclick=function(){var d=spriteDefaults(p);document.getElementById("pkSpriteFront").value=d.front;document.getElementById("pkSpriteBack").value=d.back;document.getElementById("pkSpriteIcon").value=d.icon;document.getElementById("pkSpriteScale").value=d.scale;write()}}
function init(){ensureSprites();mount();var target=document.getElementById("itemList");if(target)new MutationObserver(function(){window.setTimeout(mount,0)}).observe(target,{childList:true,subtree:true,attributes:true,classFilter:["class"]});var editor=document.getElementById("editor");if(editor)new MutationObserver(function(){if(!document.getElementById("pokerol-sprite-card"))window.setTimeout(mount,0)}).observe(editor,{childList:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
