from world.faro_ahogado_cards import (
    EXTERNAL_CONTENT_IDS,
    FARO_AHOGADO_CARDS,
    FARO_AHOGADO_CARD_VALIDATION,
    FARO_AHOGADO_INITIAL_STATE,
)


FARO_AHOGADO_CAMPAIGN = {
    "id": "CAMPAIGN-FARO-AHOGADO-VS01",
    "name": "Faro Ahogado",
    "canon_status": "vertical_slice",
    "campaign_note": "Faro Ahogado es una campaña reactiva. Este ID no representa una Room ni un lugar del mapa.",
    "premise": (
        "El Culto de las Arañas sustituye habitantes por Alternos para contaminar la reliquia del templo-faro; "
        "la sustitución y la Niebla degradan progresivamente la percepción y la psique del pueblo."
    ),
    "objective": {
        "id": "FA-OBJECTIVE-EXPEDITION",
        "text": "Descubrir la sustitución del pueblo, asegurar acceso al Faro Ahogado y activar la Linterna Etérica para detener la contaminación de la reliquia.",
        "completion_authority": "WORLD_ENGINE_EVIDENCE",
    },
    "content_contract": {
        "card_count": 14,
        "card_validation": FARO_AHOGADO_CARD_VALIDATION,
        "initial_state": FARO_AHOGADO_INITIAL_STATE,
        "external_content_dependencies": sorted(EXTERNAL_CONTENT_IDS),
        "adventure_cards": FARO_AHOGADO_CARDS,
        "stat_bridge": {"printed_POW": "FUE", "printed_DEF": "TCG_OR_ENCOUNTER_DEF", "shared": ["PSI", "PER"], "equipment": ["DRIVER"]},
    },
    "beats": [
        {
            "id": "FA-BEAT-LEAD",
            "name": "Indicio fiable",
            "state_goal": "El mundo contiene evidencia verificable de que una persona fue sustituida por un Alterno.",
            "completion_authority": "WORLD_ENGINE_EVIDENCE",
            "completion_conditions": [{"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "REPLACEMENT_PROOF"}],
        },
        {
            "id": "FA-BEAT-ROUTE",
            "name": "Ruta viable",
            "state_goal": "El jugador identifica mediante evidencia una ruta costera o la red física utilizada por el Culto.",
            "completion_authority": "WORLD_ENGINE_EVIDENCE",
            "completion_conditions": [{"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "ROUTE_IDENTIFIED"}],
        },
        {
            "id": "FA-BEAT-MEANS",
            "name": "Medios para partir",
            "state_goal": "El mundo confirma que el jugador posee Linterna, acceso y medios suficientes para alcanzar el Faro.",
            "completion_authority": "WORLD_ENGINE_EVIDENCE",
            "completion_conditions": [{"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "EXPEDITION_MEANS_SECURED"}],
        },
        {
            "id": "FA-BEAT-CROSSING",
            "name": "Tramo peligroso",
            "state_goal": "Una confrontación autorizada elimina o contiene la amenaza que bloquea la resolución del Faro.",
            "completion_authority": "WORLD_ENGINE_EVIDENCE",
            "completion_conditions": [{"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "CLIMAX_THREAT_RESOLVED"}],
        },
        {
            "id": "FA-BEAT-CLIMAX",
            "name": "Resolución de la expedición",
            "state_goal": "El Faro queda activado y el Master es exiliado por una resolución autoritativa del World Engine.",
            "completion_authority": "WORLD_ENGINE_EVIDENCE",
            "completion_conditions": [{"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "FARO_RESOLVED"}],
        },
    ],
    "signal_projections": [
        {"signal": "attention", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "PUBLIC_HARM_OR_COERCION"}},
        {"signal": "replacement", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "REPLACEMENT_PROOF"}},
        {"signal": "route", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "ROUTE_IDENTIFIED"}},
        {"signal": "means", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "EXPEDITION_MEANS_SECURED"}},
        {"signal": "climax", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "CLIMAX_THREAT_RESOLVED"}},
        {"signal": "faro", "mode": "INCREMENT", "value": 1, "when": {"source": "EVIDENCE", "path": "campaign_milestones", "op": "contains", "value": "FARO_RESOLVED"}},
    ],
    "deck": [
        {
            "id": "FA-CARD-LEAD-SOURCE",
            "type": "OPPORTUNITY",
            "name": "Fuente de información disponible",
            "enabled": True,
            "priority": 80,
            "active_beats": ["FA-BEAT-LEAD"],
            "relevance_terms": ["pregunto", "averiguo", "investigo", "rumor", "expedicion", "expedición", "faro"],
            "world_queries": [
                "local_entities_with_relevant_knowledge",
                "active_facts_related_to_campaign_lead",
                "visible_documents_or_objects_with_relevant_information",
            ],
            "worldbook_topics": [
                "Faro Ahogado",
                "expediciones y rutas relevantes al contexto local",
            ],
            "director_intent": "FIND_EXISTING_SOURCE_FOR_LEAD",
            "content_card_ids": ["FA-CARD-LA-NINA-DE-LAS-FLORES", "FA-CARD-ALDEANOS-PARANOICOS", "FA-CARD-PESCADOR-OLVIDO-MAR"],
        },
        {
            "id": "FA-CARD-LEAD-PRESSURE",
            "type": "PRESSURE",
            "name": "La oportunidad puede cerrarse",
            "enabled": True,
            "priority": 45,
            "active_beats": ["FA-BEAT-LEAD"],
            "world_queries": [
                "active_local_events",
                "actors_with_goals_that_can_change_access_to_information",
            ],
            "worldbook_topics": ["autoridades, instituciones y rutinas locales relevantes"],
            "director_intent": "EVALUATE_EXISTING_PRESSURE_ON_INFORMATION_ACCESS",
            "content_card_ids": ["FA-CARD-VOZ-EN-LA-NIEBLA", "FA-CARD-ROSTRO-DE-NADIE"],
        },
        {
            "id": "FA-CARD-ROUTE-EVIDENCE",
            "type": "OPPORTUNITY",
            "name": "Convertir la pista en una ruta",
            "enabled": True,
            "priority": 85,
            "active_beats": ["FA-BEAT-ROUTE"],
            "requires_beats": ["FA-BEAT-LEAD"],
            "relevance_terms": ["ruta", "mapa", "camino", "llegar", "seguir", "navegar", "acceso"],
            "world_queries": [
                "player_active_facts_supporting_route_inference",
                "local_route_objects_and_exits",
                "npcs_with_route_or_access_knowledge",
            ],
            "worldbook_topics": [
                "geografia y desplazamiento relevante a la expedicion",
                "restricciones de viaje y acceso",
            ],
            "director_intent": "ASSEMBLE_ROUTE_FROM_EXISTING_EVIDENCE",
            "content_card_ids": ["FA-CARD-PESCADOR-OLVIDO-MAR", "FA-CARD-PROCESION-SIN-ROSTROS"],
        },
        {
            "id": "FA-CARD-ROUTE-ALTERNATIVE",
            "type": "OPPORTUNITY",
            "name": "Vía alternativa",
            "enabled": True,
            "priority": 55,
            "active_beats": ["FA-BEAT-ROUTE"],
            "requires_beats": ["FA-BEAT-LEAD"],
            "relevance_terms": ["otra forma", "alternativa", "rodear", "engañar", "robar", "comprar", "convencer"],
            "world_queries": [
                "alternative_local_capabilities",
                "relationships_or_factions_that_can_change_access",
                "objects_or_documents_that_can_change_route_options",
            ],
            "worldbook_topics": ["formas institucionales, comerciales y clandestinas de acceso relevantes"],
            "director_intent": "SEARCH_FOR_EXISTING_ALTERNATE_ROUTE",
            "content_card_ids": ["FA-CARD-VISION-DEL-AGUA", "FA-CARD-CAPILLA-HUNDIDA"],
        },
        {
            "id": "FA-CARD-MEANS-ACCESS",
            "type": "OPPORTUNITY",
            "name": "Medios de ejecución",
            "enabled": True,
            "priority": 85,
            "active_beats": ["FA-BEAT-MEANS"],
            "requires_beats": ["FA-BEAT-ROUTE"],
            "relevance_terms": ["conseguir", "necesito", "permiso", "barco", "transporte", "equipo", "pagar", "aliado"],
            "world_queries": [
                "required_resources_for_current_route",
                "local_owners_or_authorities_of_required_resources",
                "jobs_relationships_or_transactions_that_can_grant_access",
            ],
            "worldbook_topics": ["recursos, transporte, autoridad y economia relevantes a la ruta elegida"],
            "director_intent": "FIND_EXISTING_MEANS_TO_EXECUTE_ROUTE",
            "content_card_ids": ["FA-CARD-CAPILLA-HUNDIDA", "FA-CARD-FARO-AHOGADO"],
        },
        {
            "id": "FA-CARD-MEANS-PRESSURE",
            "type": "PRESSURE",
            "name": "Costo de demora",
            "enabled": True,
            "priority": 50,
            "active_beats": ["FA-BEAT-MEANS"],
            "requires_beats": ["FA-BEAT-ROUTE"],
            "world_queries": [
                "time_sensitive_local_events",
                "resource_availability_changes",
                "competing_actor_goals_relevant_to_campaign",
            ],
            "worldbook_topics": ["ritmos de trabajo, viaje y disponibilidad relevantes"],
            "director_intent": "EVALUATE_EXISTING_TIME_OR_RESOURCE_PRESSURE",
            "content_card_ids": ["FA-CARD-PORTAVOZ-SEDA-NEGRA", "FA-CARD-PROCESION-SIN-ROSTROS"],
        },
        {
            "id": "FA-CARD-CONSEQUENCE-ATTENTION",
            "type": "CONSEQUENCE",
            "name": "Atención acumulada",
            "enabled": True,
            "priority": 90,
            "active_beats": ["FA-BEAT-LEAD", "FA-BEAT-ROUTE", "FA-BEAT-MEANS", "FA-BEAT-CROSSING"],
            "conditions": [
                {"source": "CAMPAIGN", "path": "signals.attention", "op": "gte", "value": 1}
            ],
            "relevance_terms": ["robo", "rompo", "amenazo", "ataco", "engaño", "engano", "fuerzo"],
            "world_queries": [
                "world_consequences_already_created_by_player_actions",
                "affected_npcs_factions_and_authorities",
            ],
            "worldbook_topics": ["autoridad y respuesta social relevante a las consecuencias existentes"],
            "director_intent": "SURFACE_EXISTING_CONSEQUENCES",
            "content_card_ids": ["FA-CARD-VECINO-REEMPLAZADO", "FA-CARD-ALTERNO-ROSAS-MARCHITAS"],
        },
        {
            "id": "FA-CARD-CROSSING-RISK",
            "type": "PRESSURE",
            "name": "Riesgo del trayecto",
            "enabled": True,
            "priority": 95,
            "active_beats": ["FA-BEAT-CROSSING"],
            "requires_beats": ["FA-BEAT-MEANS"],
            "world_queries": [
                "current_route_hazards",
                "active_world_events_on_or_near_route",
                "combat_eligible_hostile_or_opposed_actors",
            ],
            "worldbook_topics": ["peligros ambientales, sociales y de viaje relevantes a la ruta"],
            "director_intent": "EVALUATE_EXISTING_CROSSING_RISK",
            "content_card_ids": ["FA-CARD-ROSTRO-DE-NADIE", "FA-CARD-ROSTRO-EN-EL-VIDRIO", "FA-CARD-PORTAVOZ-SEDA-NEGRA"],
        },
        {
            "id": "FA-CARD-CROSSING-RESOURCE",
            "type": "OPPORTUNITY",
            "name": "Recurso durante el trayecto",
            "enabled": True,
            "priority": 60,
            "active_beats": ["FA-BEAT-CROSSING"],
            "requires_beats": ["FA-BEAT-MEANS"],
            "world_queries": [
                "nearby_shelter_resources_allies_or_alternate_paths",
                "player_knowledge_relevant_to_current_hazard",
            ],
            "worldbook_topics": ["recursos y prácticas útiles ante el peligro actual"],
            "director_intent": "FIND_EXISTING_CROSSING_OPPORTUNITY",
            "content_card_ids": ["FA-CARD-VISION-DEL-AGUA", "FA-CARD-NINA-DE-LAS-FLORES-CREATURE"],
        },
        {
            "id": "FA-CARD-CLIMAX-CONTEXT",
            "type": "BEAT",
            "name": "Preparar la resolución final",
            "enabled": True,
            "priority": 100,
            "active_beats": ["FA-BEAT-CLIMAX"],
            "requires_beats": ["FA-BEAT-CROSSING"],
            "world_queries": [
                "authoritative_campaign_climax_state",
                "present_entities_objects_facts_and_events_relevant_to_final_resolution",
            ],
            "worldbook_topics": ["canon estrictamente relevante al objetivo final de Faro Ahogado"],
            "director_intent": "ASSEMBLE_FINAL_CONTEXT_WITHOUT_INVENTING_STATE",
            "content_card_ids": ["FA-CARD-FARO-AHOGADO"],
        },
    ],
}

from services.dm_campaign_registry import register_campaign

register_campaign(FARO_AHOGADO_CAMPAIGN)
