'use strict';
const $=id=>document.getElementById(id), now=()=>new Date().toISOString(), uid=p=>p+'_'+(crypto.randomUUID?crypto.randomUUID():(Date.now().toString(36)+Math.random().toString(36).slice(2)));
const STORE='dem_v05_state', CFG='dem_v05_cfg';
function baseState(){const pid='project_money_hunt';return{version:5,activeProjectId:pid,projects:[{id:pid,name:'Money Hunt',product:'Money Hunt',objective:'Recover $100 real revenue and reach 100 activated users.',landing:'',brand:{audience:'Freelancers and solo service businesses.',voice:'Direct, practical, financially concrete. No hype.',promise:'Turn money already earned but still pending into a clear next recovery action.',forbidden:'Do not claim guaranteed recovery, banking, accounting, tax or legal functionality.'},created_at:now()}],campaigns:[],experiments:[],jobs:[],orders:[],results:[],assets:[],creatives:[],approvals:[],publications:[],events:[],insights:[],audit:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');return x&&x.version===5?x:baseState()}catch{return baseState()}}
function loadCfg(){try{return Object.assign({gc:'http://127.0.0.1:7865',ollama:'http://127.0.0.1:11434',model:'qwen3:8b',publish:'',metrics:''},JSON.parse(localStorage.getItem(CFG)||'{}'))}catch{return{gc:'http://127.0.0.1:7865',ollama:'http://127.0.0.1:11434',model:'qwen3:8b',publish:'',metrics:''}}}
let S=load(), C=loadCfg(), health={gc:false,llm:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const project=()=>S.projects.find(x=>x.id===S.activeProjectId)||S.projects[0];
const activeCampaign=()=>S.campaigns.find(x=>x.project_id===project().id&&x.status==='ACTIVE')||S.campaigns.filter(x=>x.project_id===project().id).at(-1)||null;
const exps=()=>S.experiments.filter(x=>x.project_id===project().id);
const jobs=()=>S.jobs.filter(x=>x.project_id===project().id);
const creatives=()=>S.creatives.filter(x=>x.project_id===project().id);
const pubs=()=>S.publications.filter(x=>x.project_id===project().id);
const events=()=>S.events.filter(x=>x.project_id===project().id);
function log(type,entity,id,payload={}){S.audit.unshift({id:uid('audit'),project_id:project().id,type,entity,entity_id:id,payload,created_at:now()});S.audit=S.audit.slice(0,1000)}
function save(render=true){localStorage.setItem(STORE,JSON.stringify(S));if(render)R()}
function saveCfg(){localStorage.setItem(CFG,JSON.stringify(C));sessionStorage.setItem('dem_publish_token',$('publishToken').value||'');sessionStorage.setItem('dem_metrics_token',$('metricsToken').value||'')}
function toast(text,err=false){$('msg').textContent=text;$('msg').className='msg'+(err?' err':'');setTimeout(()=>$('msg').classList.add('hidden'),5500)}
function download(name,data,type='application/json'){const b=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function copy(text){navigator.clipboard.writeText(text).then(()=>toast('Copiado')).catch(()=>toast('No se pudo copiar',true))}
function findAsset(id){return S.assets.find(x=>x.id===id)}function findCreative(id){return S.creatives.find(x=>x.id===id)}function findExp(id){return S.experiments.find(x=>x.id===id)}
function approval(c){return S.approvals.find(a=>a.creative_id===c.id&&a.revision===c.revision&&a.decision==='APPROVED')}
async function fetchJson(url,opt={},timeout=3500){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(url,{...opt,signal:ctrl.signal,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||d.error||r.status+' '+r.statusText);return d}finally{clearTimeout(t)}}
async function testGC(show=false){$('gcInfo').textContent='Checking...';try{const d=await fetchJson(C.gc.replace(/\/$/,'')+'/api/status');health.gc=true;$('gcInfo').textContent=(d.lab_version?'v'+d.lab_version+' · ':'')+(d.hardware?.gpu||'GC online')+' · '+(d.stage||'ready');if(show)toast('Generation Core conectado')}catch(e){health.gc=false;$('gcInfo').textContent='No accesible desde este navegador: '+e.message;if(show)toast('GC no accesible; DEM usará BRIDGED',true)}badges();return health.gc}
async function testLLM(show=false){$('llmInfo').textContent='Checking...';try{const d=await fetchJson(C.ollama.replace(/\/$/,'')+'/api/tags');health.llm=Array.isArray(d.models);$('llmInfo').textContent=health.llm?d.models.map(x=>x.name).slice(0,4).join(', '):'Respuesta no reconocida';if(show)toast('Ollama conectado')}catch(e){health.llm=false;$('llmInfo').textContent='No accesible: '+e.message;if(show)toast('LLM no accesible; DEM usará reglas internas',true)}badges();return health.llm}
function badges(){$('gcBadge').textContent='GC · '+(health.gc?'NATIVE':'BRIDGED');$('gcBadge').className='badge '+(health.gc?'ok':'warn');$('llmBadge').textContent='LLM · '+(health.llm?'NATIVE':'RULES');$('llmBadge').className='badge '+(health.llm?'ok':'warn')}
async function ollama(prompt){if(!health.llm)throw Error('Ollama offline');const body={model:C.model,prompt,stream:false,format:'json',options:{temperature:.3}};const d=await fetchJson(C.ollama.replace(/\/$/,'')+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},25000);return JSON.parse(d.response)}
function defaultVariants(){return[{name:'Loss aversion',framing:'Stop losing money you already earned.',hypothesis:'Loss framing increases click intent.',hook:'You already did the work. Why is the money still missing?'},{name:'Found money',framing:"Find money you've already earned.",hypothesis:'Recovered-value framing increases activation.',hook:'How much money have you already earned but not collected?'},{name:'Forgotten receivables',framing:'How much money are you forgetting to collect?',hypothesis:'Question framing increases self-identification.',hook:'Your next $100 may already be sitting in unpaid work.'}]}
async function createExperiments(){let camp=activeCampaign();if(!camp){toast('Guarde una campaña primero',true);return}let vars=defaultVariants();if(health.llm){try{const p=project(),q=`Return JSON only: {"variants":[{"name":"","framing":"","hypothesis":"","hook":""}]}. Create exactly 3 acquisition experiment variants for ${p.product}. Audience: ${p.brand.audience}. Promise: ${p.brand.promise}. Campaign objective: ${camp.objective}. Constraints: ${p.brand.forbidden}.`;const d=await ollama(q);if(Array.isArray(d.variants)&&d.variants.length>=3)vars=d.variants.slice(0,3)}catch{}}
for(const v of vars){S.experiments.push({id:uid('exp'),project_id:project().id,campaign_id:camp.id,name:v.name,framing:v.framing,hypothesis:v.hypothesis,hook:v.hook,status:'ACTIVE',created_at:now()})}log('EXPERIMENT_BATCH_CREATED','campaign',camp.id,{count:3,engine:health.llm?'ollama':'rules'});save();toast('3 experimentos creados')}
function jobPrompt(e){const p=project(),camp=S.campaigns.find(c=>c.id===e.campaign_id);return `Create a vertical 9:16 acquisition creative for ${p.product}.\nAudience: ${p.brand.audience}\nCampaign objective: ${camp?.objective||p.objective}\nFraming: ${e.framing}\nHook: ${e.hook}\nCore promise: ${p.brand.promise}\nVoice: ${p.brand.voice}\nCTA: Try Money Hunt\nConstraints: ${p.brand.forbidden}\nDesign: strong mobile hierarchy, readable headline, clear money-recovery concept, room for CTA, no fake logos, no unreadable UI.`}
function createBatch(){const es=exps().filter(e=>e.status==='ACTIVE');if(!es.length){toast('No hay experimentos activos',true);return}let n=0;for(const e of es){if(S.jobs.some(j=>j.experiment_id===e.id&&['PENDING','RUNNING','BRIDGED_WAITING_ASSET','SUCCEEDED'].includes(j.status)))continue;const j={id:uid('job'),project_id:project().id,campaign_id:e.campaign_id,experiment_id:e.id,type:'creative_generation',prompt:jobPrompt(e),negative_prompt:'watermark, unreadable text, fake logos, clutter, distorted UI',aspect_ratio:'9:16',steps:24,guidance_scale:7,status:'PENDING',mode:null,error:null,created_at:now()};S.jobs.unshift(j);log('JOB_CREATED','job',j.id,{experiment_id:e.id});n++}save();toast(n+' Job(s) creados');for(const j of jobs().filter(j=>j.status==='PENDING'))executeJob(j.id)}
async function executeJob(id){const j=S.jobs.find(x=>x.id===id);if(!j)return;if(health.gc){j.status='RUNNING';j.mode='NATIVE';log('JOB_STARTED','job',j.id,{mode:'NATIVE'});save();try{const d=await fetchJson(C.gc.replace(/\/$/,'')+'/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:j.prompt,negative_prompt:j.negative_prompt,seed:null,count:1,aspect_ratio:j.aspect_ratio,steps:j.steps,guidance_scale:j.guidance_scale,reference_image_base64:null,strength:.65})},180000);const out=d.outputs?.[0];if(!out?.image_base64)throw Error('GC respondió sin output');acceptAsset(j,'data:image/png;base64,'+out.image_base64,{provider:'Generation Core',seed:out.seed,width:out.width,height:out.height,runtime_seconds:out.runtime_seconds});toast('Asset generado por Generation Core')}catch(e){j.status='FAILED';j.error=e.message;log('JOB_FAILED','job',j.id,{error:e.message});save();toast(e.message,true)}}else bridgeJob(j)}
function bridgeJob(j){let o=S.orders.find(x=>x.job_id===j.id&&x.status==='OPEN');if(!o){o={id:uid('order'),project_id:j.project_id,job_id:j.id,experiment_id:j.experiment_id,status:'OPEN',prompt:j.prompt,negative_prompt:j.negative_prompt,aspect_ratio:j.aspect_ratio,deliverable:'1 final PNG/JPG, vertical 9:16, no watermark',created_at:now()};S.orders.unshift(o)}j.status='BRIDGED_WAITING_ASSET';j.mode='BRIDGED';j.error=null;log('PRODUCTION_ORDER_CREATED','order',o.id,{job_id:j.id});save()}
function acceptAsset(j,url,meta={}){const rid=uid('result'),aid=uid('asset'),e=findExp(j.experiment_id),c={id:uid('creative'),project_id:j.project_id,campaign_id:j.campaign_id,experiment_id:j.experiment_id,job_id:j.id,asset_id:aid,revision:1,copy:e?.hook||e?.framing||'',cta:'Try Money Hunt',channel:'instagram',status:'REVIEW',created_at:now()};S.results.unshift({id:rid,project_id:j.project_id,job_id:j.id,status:'SUCCEEDED',metadata:meta,created_at:now()});S.assets.unshift({id:aid,project_id:j.project_id,result_id:rid,job_id:j.id,url,media_type:'image/*',metadata:meta,created_at:now()});S.creatives.unshift(c);j.status='SUCCEEDED';j.error=null;const o=S.orders.find(x=>x.job_id===j.id&&x.status==='OPEN');if(o)o.status='FULFILLED';log('ASSET_RECEIVED','asset',aid,{job_id:j.id,mode:j.mode});log('CREATIVE_CREATED','creative',c.id,{revision:1});save()}
window.uploadAsset=id=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=()=>{const f=inp.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const j=S.jobs.find(x=>x.id===id);acceptAsset(j,r.result,{provider:'BRIDGED',filename:f.name,size:f.size});toast('Asset real recibido; Job completado')};r.readAsDataURL(f)};inp.click()};
window.copyOrder=id=>{const o=S.orders.find(x=>x.id===id);copy(`PRODUCTION ORDER ${o.id}\n\n${o.prompt}\n\nNegative: ${o.negative_prompt}\nAspect: ${o.aspect_ratio}\nDeliverable: ${o.deliverable}`)};
window.downloadOrder=id=>{const o=S.orders.find(x=>x.id===id);download(o.id+'.json',JSON.stringify(o,null,2))};
window.retryJob=id=>executeJob(id);
window.editCreative=id=>{const c=findCreative(id);const v=prompt('Copy',c.copy);if(v===null)return;const t=prompt('CTA',c.cta);if(t===null)return;c.copy=v;c.cta=t;c.revision++;c.status='REVIEW';log('CREATIVE_REVISED','creative',c.id,{revision:c.revision});save()};
window.approveCreative=(id,decision)=>{const c=findCreative(id);S.approvals.unshift({id:uid('approval'),project_id:c.project_id,creative_id:c.id,revision:c.revision,decision,created_at:now()});c.status=decision;log(decision==='APPROVED'?'CONTENT_APPROVED':'CONTENT_REJECTED','creative',c.id,{revision:c.revision});save()};
function trackedUrl(c,pid){const p=project(),base=p.landing||activeCampaign()?.landing||'';if(!base)return'';try{const u=new URL(base);u.searchParams.set('utm_source',c.channel||'social');u.searchParams.set('utm_medium','organic');u.searchParams.set('utm_campaign',c.campaign_id||'campaign');u.searchParams.set('utm_content',pid);return u.toString()}catch{return base}}
window.queuePublication=id=>{const c=findCreative(id);if(!approval(c)){toast('Bloqueado: esa revisión no está APPROVED',true);return}if(S.publications.some(p=>p.creative_id===id&&p.revision===c.revision))return toast('Ya existe Publication para esta revisión',true);const p={id:uid('pub'),project_id:c.project_id,campaign_id:c.campaign_id,experiment_id:c.experiment_id,creative_id:c.id,revision:c.revision,channel:c.channel,status:C.publish?'READY_NATIVE':'READY_BRIDGED',mode:C.publish?'NATIVE':'BRIDGED',scheduled_at:null,remote_url:null,remote_id:null,created_at:now()};p.tracked_url=trackedUrl(c,p.id);S.publications.unshift(p);log('PUBLICATION_QUEUED','publication',p.id,{mode:p.mode});save();toast('Publication en queue')};
function packageForPub(p){const c=findCreative(p.creative_id),a=findAsset(c.asset_id);return{publication_id:p.id,project_id:p.project_id,campaign_id:p.campaign_id,experiment_id:p.experiment_id,creative_id:c.id,revision:c.revision,channel:p.channel,copy:c.copy,cta:c.cta,asset_url:a.url,landing_url:p.tracked_url,scheduled_at:p.scheduled_at}}
window.downloadPackage=id=>{const p=S.publications.find(x=>x.id===id);download('publication-'+p.id+'.json',JSON.stringify(packageForPub(p),null,2))};
window.copyPost=id=>{const p=S.publications.find(x=>x.id===id),c=findCreative(p.creative_id);copy(c.copy+'\n\n'+c.cta+(p.tracked_url?'\n'+p.tracked_url:''))};
window.registerPublished=id=>{const p=S.publications.find(x=>x.id===id),u=prompt('URL real de la publicación');if(!u)return;p.remote_url=u;p.status='PUBLISHED';p.published_at=now();log('CONTENT_PUBLISHED','publication',p.id,{remote_url:u,mode:'BRIDGED'});save()};
window.publishNative=async id=>{const p=S.publications.find(x=>x.id===id);if(!C.publish)return registerPublished(id);try{p.status='PUBLISHING';save();const token=sessionStorage.getItem('dem_publish_token')||'';const d=await fetchJson(C.publish,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(packageForPub(p))},30000);p.remote_url=d.remote_url||d.url||null;p.remote_id=d.remote_id||d.id||null;p.status='PUBLISHED';p.published_at=now();log('CONTENT_PUBLISHED','publication',p.id,{mode:'NATIVE',remote_url:p.remote_url});save();toast('Publicado por conector')}catch(e){p.status='FAILED';p.error=e.message;log('PUBLICATION_FAILED','publication',p.id,{error:e.message});save();toast(e.message,true)}};
